### ISSUE TITLE
Trying to build with ms studio

### ISSUE THREAD

**Issue by MattL0** [legrego/HSPI_TwilioMessaging#10]
ok was able to build

**Comment by MattL0** [comment]
The version i got from this is 0.1 

but i see on github it is supposed to be v.2

Is there something oi am mising?

thanks

**Comment by MattL0** [comment]
And ms studiocomplains about this :

I had to mannually install this version to build the exe? 

https://www.nuget.org/packages/Fody/2.1.0

**Comment by legrego** [comment]
I must have a version discrepancy, because 0.1.0 is the correct one. I’ll fix that!

How did you resolve the fody issue? Did nuget install it for you, or were other steps involved?

**Comment by MattL0** [comment]
Sorry for reoppening this now. I had to manualy  download the nugget package .

Will test the plugin next month. Thank you.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
