### ISSUE TITLE
Triggers

### ISSUE THREAD

**Issue by MattL0** [legrego/HSPI_TwilioMessaging#18]
Thanks for this very nice plugin!.

I would l;ike to know, When i will be out of the trials.... is the trigger gonna be faster? because now it's take somewhat 10 seconds for the trigger to fire the hs event.

Thanks

**Comment by MattL0** [comment]
+ When i iten a text as a triggers and click ''Submit'' it always return to ''cheked''
![Capture](https://user-images.githubusercontent.com/27497561/56854886-b1335980-690b-11e9-84a4-e9ba9339eda1.PNG)
![1](https://user-images.githubusercontent.com/27497561/56854888-b42e4a00-690b-11e9-908a-53e13172ccb4.PNG)

**Comment by legrego** [comment]
Hey @MattL0,

Thanks for using this plugin! I hope you find it useful!

> I would like to know, When i will be out of the trials.... is the trigger gonna be faster? because now it's take somewhat 10 seconds for the trigger to fire the hs event.

Right now, this plugin checks for incoming messages every 15 seconds by hitting Twilio's Programmable SMS API. I have an idea for an alternative approach in #16, but it comes with its own set of complexity and tradeoffs, both from a development perspective and an end-user perspective.

> When i iten a text as a triggers and click ''Submit'' it always return to ''cheked''

Thanks for reporting this. I'll work on a fix and hopefully get a new release out shortly.

**Comment by legrego** [comment]
@MattL0 I have a fix for the trigger inputs submitted to HomeSeer. Version 0.2.2 (once released) will have the fix applied. Thanks again for the report!
