### ISSUE TITLE
Update Required

### ISSUE THREAD

**Issue by wvalko** [legrego/HSPI_TwilioMessaging#20]
Was excited to find this plugin, trying to add to WAF and give her SMS updated when the dryer is done.  BUT When I run a test I receive an 'Update Required' error?

**Comment by legrego** [comment]
Hey @wvalko,

Can you enable debug logging and post the logs from the HS log viewer when you run the test? Please redact any sensitive info. Thanks!

**Comment by wvalko** [comment]
Thanks for the quick reply!  

I enabled the logging, you can see in the log the attempt to send msg.  

May-21 8:40:44 AM	 	Twilio Messaging	Debug:No triggers exist; aborting refresh
May-21 8:40:44 AM	 	Twilio Messaging	Debug:Refreshing Triggers
May-21 8:40:29 AM	 	Twilio Messaging	Debug:Starting SendMessageToTwilio
May-21 8:40:29 AM	 	Twilio Messaging	Debug:No triggers exist; aborting refresh
May-21 8:40:29 AM	 	Twilio Messaging	Debug:Refreshing Triggers

Unfortunately there isn't more showing than that.  Below is a snapshot of the error that is shown below the test button. 

![image](https://user-images.githubusercontent.com/29451850/58101855-f31b8c80-7ba5-11e9-8ac7-4fa1fe2bf101.png)

**Comment by legrego** [comment]
Interesting, thanks for the detail. I found this on the twilio support site: https://www.twilio.com/docs/api/errors/20426

I wonder if your machine is trying to use an incompatible cipher suite when negotiating the connection to Twilio.

Did you create your Twilio project after March 28, 2019? If so, you might be subject to [stricter connection requirements](https://support.twilio.com/hc/en-us/articles/360006751753-Tips-for-Upgrading-Your-Environment-to-Support-Twilio-REST-API-s-TLS-and-Strong-Cipher-Suite-Changes) than my account, which was created long ago. I'll do some more research to see if there's something internal to the plugin that I can change to support this, but I'll need a few days to get around to it.

**Comment by wvalko** [comment]
YES, this account was created since then..  and reading the link, looks like they'll enforce TLS 1.2 on all account starting end of June.  Thanks for the help, hoping to use this plugin!  Will look for some good news in a few days :)

**Comment by legrego** [comment]
@wvalko I published version `0.2.3` of this plugin to the HomeSeer plugin repository. Can you give that a try and let me know if it fixes your error?

After upgrading, please restart the entire machine that HomeSeer is running on. The updated Twilio dependency didn't cleanup correctly after updating for me, but a restart did the trick with my testing.

**Comment by wvalko** [comment]
Great, it worked!  Was able to successfully send a test after update/restart!

Thank you, appreciate your plugin, and helpfulness to make it operational for me!

**Comment by legrego** [comment]
Excellent! I'll close this issue then. Please feel free to suggest improvements or report bugs in the future. I'm more than happy to accommodate reasonable requests 😄
